# -*- coding: utf-8 -*-
"""Untitled0.ipynb
from fastapi import FastAPI
from pydantic import BaseModel
import openai  # O la librería del proveedor LLM que uses

app = FastAPI()

class UserQuery(BaseModel):
    message: str

# 1. Diccionario de Prompts Especializados
SPECIALIZED_PROMPTS = {
    "soporte_tecnico": "Eres un asistente de soporte técnico paciente. Analiza el error reportado y da soluciones paso a paso: {input}",
    "ventas": "Eres un asesor comercial persuasivo. Presenta las opciones de compra y beneficios para la solicitud: {input}",
    "general": "Eres un asistente servicial y conciso. Responde amablemente a: {input}"
}

# 2. Prompt del Router
ROUTER_PROMPT = """
Clasifica la consulta del usuario en exactamente UNA de las siguientes categorías:
- soporte_tecnico
- ventas
- general

Reglas:
- Responde únicamente con el nombre exacto de la categoría. No agregues puntuación ni texto adicional.

Consulta: {input}
"""

def route_intent(user_input: str) -> str:
    # Llamada rápida al modelo para clasificar
    response = openai.chat.completions.create(
        model="gpt-4o-mini", # Modelo rápido/económico para clasificar
        messages=[{"role": "user", "content": ROUTER_PROMPT.format(input=user_input)}],
        temperature=0.0
    )
    intent = response.choices[0].message.content.strip().lower()
    return intent if intent in SPECIALIZED_PROMPTS else "general"

@app.post("/chat")
def handle_chat(query: UserQuery):
    # Paso 1: Enrutamiento
    category = route_intent(query.message)
    
    # Paso 2: Selección del prompt especializado
    specialized_system_prompt = SPECIALIZED_PROMPTS[category]
    
    # Paso 3: Generación de la respuesta final
    final_response = openai.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": specialized_system_prompt.format(input=query.message)},
            {"role": "user", "content": query.message}
        ]
    )
    
    return {
        "category_detected": category,
        "response": final_response.choices[0].message.content
    }
app = FastAPI()

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwFp3mlYHyhc6BaJaW71i2nYf_JU_R8W
"""

